name: Deploy Backend Chapters to Heroku
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy chapter backends
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run |
          CHAPTER_DIRS=(24-Express-Server 25-Band-Generator))
          for dir in "Completed-Projects/${CHAPTER_DIRS[@]}"; do
            if [ -f "$dir/package.json" ]; then
              heroku apps:create ${dir//\//-} --region usa --buildpack https://github.com/timanovsky/subdir-heroku-buildpack.git
              heroku config:set PROJECT_PATH=$dir --app ${dir//\//-}
              git subtree push --prefix $dir heroku main
              echo "Deployed $dir successfully."
            else
              echo "Skipping $dir, no package.json found."
            fi
          done
